spring.application.name=notification-service
server.port = 8082
# H2 in-memory database
spring.datasource.url=jdbc:postgresql://ep-crimson-tooth-ahoryngx-pooler.c-3.us-east-1.aws.neon.tech/notification?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_4zXfRoNCg0vB
spring.sql.init.mode=always

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.notificationservice.dto.TaskEventDto
