spring.application.name=user-service

# H2 in-memory database
spring.datasource.url=jdbc:postgresql://ep-crimson-tooth-ahoryngx-pooler.c-3.us-east-1.aws.neon.tech/users?sslmode=require&channel_binding=require
spring.datasource.username= neondb_owner
spring.datasource.password= npg_4zXfRoNCg0vB
spring.sql.init.mode=always

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true


services.task-service.url=http://localhost:8081
services.notification-service.url =http://localhost:8082

spring.kafka.bootstrap-servers=localhost:9092


# H2 console (useful for debugging)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


